### ISSUE TITLE
Optionally allow algorithm to be specified in `unsign`.

### ISSUE THREAD

**Issue by malcolmsparks** [funcool/buddy-sign#21]
I think this article makes a good case for this: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by niwinz** [comment]
Hi @malcolmsparks 

Buddy already follows the recommendations of that article for a long time (maybe since the first or second public version).

No automatic algorithm detection (through header) is performed on `unsign`/`decrypt` operation. And that functions already accepts the same parameters that `sign`/`encrypt`. If no algoritm is specified for `unsign`/`decrypt` the default will be used (the same default if you don't pass any argument to `sign`/`encrypt`.
