### ISSUE TITLE
Buddy 1.0.0 throws exception for previously working code

### ISSUE THREAD

**Issue by rationalism** [funcool/buddy-sign#32]
Here's one of the functions I'm using for authentication with Buddy:

(def encryption {:alg :rsa-oaep :enc :a192gcm})
(def pubkey (keys/public-key "pubkey.pem"))
(def exp-hours 3)

(defn make-id-token [id]
  {:token
   (jwe/encrypt {:user {:id id}
                 :exp (-> exp-hours hours from-now)}
                pubkey encryption)})

This code apparently works fine with Buddy 0.13.0. However, with the recent Buddy 1.0.0, it throws this exception:

1. Unhandled java.lang.IllegalArgumentException
   No implementation of method: :-to-bytes of protocol:
   #'buddy.core.codecs/IByteArray found for class:
   clojure.lang.PersistentArrayMap

          core_deftype.clj:  568  clojure.core/-cache-protocol-fn
          core_deftype.clj:  560  clojure.core/-cache-protocol-fn
                codecs.clj:   60  buddy.core.codecs/eval20085/fn/G
                codecs.clj:   69  buddy.core.codecs/to-bytes
                codecs.clj:   66  buddy.core.codecs/to-bytes
                   jwe.clj:   77  buddy.sign.jwe/encode-payload
                   jwe.clj:   75  buddy.sign.jwe/encode-payload
                   jwe.clj:  224  buddy.sign.jwe/encrypt
                   jwe.clj:  214  buddy.sign.jwe/encrypt
               RestFn.java:  442  clojure.lang.RestFn/invoke

**Comment by FreekPaans** [comment]
This is probably the same issue as #30. There was an API change in 1.0.0 that requires you to change your references to `clojure.sign.jwe` by `clojure.sign.jwt`.

**Comment by niwinz** [comment]
Yes, this is already documented in https://github.com/funcool/buddy-sign/blob/master/CHANGES.adoc#version-100

I'm using semantic version so  you should read the changelog when you are upgrading to a major release. That changes are made because the previous jws/jwe/jwt impl was incomplete and now is fully compliant with the RFC and it can't be done without breaking some api. 

Although the migration path is pretty simple, just rename your import.
