### ISSUE TITLE
Suggestions for resolving lein deps :tree?

### ISSUE THREAD

**Issue by xpe** [funcool/buddy-sign#4]
Is the following a result of anything under buddy-sign's control? I'm not clear yet on the general rule for resolving `lein deps :tree` confusion; e.g. is it a downstream app's responsibility, or is it a symptom of a library needing to be more careful? Here is sample output from a project that uses buddy-sign:

```
❯ lein deps :tree
Possibly confusing dependencies found:
[ring/ring-core "1.3.2"] -> [org.clojure/tools.reader "0.8.1"]
 overrides
[buddy/buddy-auth "0.5.0"] -> [buddy/buddy-sign "0.5.0"] -> [com.taoensso/nippy "2.8.0"] -> [com.taoensso/encore "1.21.0"] -> [org.clojure/tools.reader "0.8.13"]
 and
[buddy/buddy-sign "0.5.0"] -> [com.taoensso/nippy "2.8.0"] -> [com.taoensso/encore "1.21.0"] -> [org.clojure/tools.reader "0.8.13"]
 and
[buddy/buddy-auth "0.5.0"] -> [buddy/buddy-sign "0.5.0"] -> [com.taoensso/nippy "2.8.0"] -> [org.clojure/tools.reader "0.8.13"]
 and
[buddy/buddy-sign "0.5.0"] -> [com.taoensso/nippy "2.8.0"] -> [org.clojure/tools.reader "0.8.13"]
 and
[clj-http "1.1.0"] -> [org.clojure/tools.reader "0.8.16" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[buddy/buddy-auth "0.5.0" :exclusions [org.clojure/tools.reader]]
[buddy/buddy-sign "0.5.0" :exclusions [org.clojure/tools.reader]]
[buddy/buddy-auth "0.5.0" :exclusions [org.clojure/tools.reader]]
[buddy/buddy-sign "0.5.0" :exclusions [org.clojure/tools.reader]]
[clj-http "1.1.0" :exclusions [org.clojure/tools.reader]]
```

**Comment by niwibe** [comment]
Thank you very much for report it! 

I'll solve it in the next version.

**Comment by niwibe** [comment]
Hmm, I have analized this problem, and it can not be solved by the library. 

The `buddy-sign` depends on `nippy` and `nippy` depends on `tools.reader` (0.8.13)

Your application additionally depends on clj-http and ring-core, that has dependencies to different versions of `tools.reader`. I can not set the exclusion in the library because I can not supose that the user will use `tools.reader`.

My recommendation is set a concrete version of tools.reader and exclude any other possible versions. Is a very common problem in clojure and maven, when different libraries requires different versions of the same dependency.
